export enum Meta {
  Sinister = "sinister",
  Ferocious = "ferocious",
  Timeless = "timeless",
  Fusion = "fusion",
  Rose = "rose",
  Toxic = "toxic",
  Voyager = "voyager",
  Forest = "forest",
  Sorcerous = "sorcerous",
  Catacomb = "catacomb",
  Sunrise = "sunrise",
  Halloween = "halloween",
  GoBattleLeague = "gobattle",
  Premier = "premier",
}
